"""init_all_tables

Revision ID: f15581dc7487
Revises: 
Create Date: 2026-08-21 00:50:22.137772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f15581dc7487'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='所属帖子ID'),
    sa.Column('root_id', sa.BigInteger(), nullable=True, comment='根评论ID（NULL=一级评论；非NULL=属于该根评论的回复线程）'),
    sa.Column('author_id', sa.BigInteger(), nullable=False, comment='评论者ID'),
    sa.Column('reply_user_id', sa.BigInteger(), nullable=True, comment="被回复者ID（NULL=一级评论；非NULL=前端展示'回复 @xxx'）"),
    sa.Column('content', sa.String(length=1000), nullable=False, comment='评论内容'),
    sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='点赞数'),
    sa.Column('reply_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='回复数（仅 root_id IS NULL 的一级评论维护，冗余计数）'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='0-删除 1-正常'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='编辑时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_author_id'), table_name='post_comment')
    op.drop_index(op.f('idx_post_id'), table_name='post_comment')
    op.drop_table('post_comment')
    op.alter_column('dm_conversation', 'user1_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='较小用户ID',
               existing_comment='较小用户 ID（约定 user1_id < user2_id）',
               existing_nullable=False)
    op.alter_column('dm_conversation', 'user2_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='另一用户ID',
               existing_nullable=False)
    op.alter_column('dm_conversation', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('dm_conversation', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'dm_conversation',
        existing_comment='私信会话表',
        schema=None
    )
    op.alter_column('dm_message', 'conversation_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联会话ID',
               existing_nullable=False)
    op.alter_column('dm_message', 'from_user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='发送者用户ID',
               existing_comment='发送者',
               existing_nullable=False)
    op.alter_column('dm_message', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('dm_message', 'is_read',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='0-未读 1-已读',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('dm_message', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='发送时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'dm_message',
        existing_comment='私信消息表',
        schema=None
    )
    op.alter_column('interview', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('interview', 'resume_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='使用的简历ID',
               existing_comment='使用的简历 ID',
               existing_nullable=False)
    op.alter_column('interview', 'type',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='1-完整面试 2-快速面试',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('interview', 'status',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='0-进行中 1-已完成 2-已中断',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview', 'total_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='面试总时长(秒)',
               existing_comment='面试总时长（秒）',
               existing_nullable=True)
    op.alter_column('interview', 'follow_up_count',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='追问次数（冗余计数）',
               existing_comment='追问次数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview', 'device_check_passed',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='设备检测是否通过',
               existing_comment='设备检测是否通过 0-未通过 1-已通过',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('interview', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'interview',
        existing_comment='面试会话表',
        schema=None
    )
    op.alter_column('interview_question', 'interview_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联面试ID',
               existing_nullable=False)
    op.alter_column('interview_question', 'question_type',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='1-技术题 2-项目题 3-行为题',
               existing_nullable=False)
    op.alter_column('interview_question', 'category',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='题目维度 1-技术基础 2-项目经验 3-综合素质 4-架构设计',
               existing_nullable=True)
    op.alter_column('interview_question', 'is_follow_up',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='是否追问题 0-否 1-是',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview_question', 'parent_question_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='父题目ID（追问关联）',
               existing_comment='父题目ID（追问关联，指向 interview_question.id）',
               existing_nullable=True)
    op.alter_column('interview_question', 'question_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='题目内容',
               existing_nullable=False)
    op.alter_column('interview_question', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='用户回答文本',
               existing_comment='用户回答',
               existing_nullable=True)
    op.alter_column('interview_question', 'answer_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='回答时长(秒)',
               existing_comment='回答时长（秒）',
               existing_nullable=True)
    op.alter_column('interview_question', 'thinking_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='思考时长(秒)',
               existing_comment='思考时长（秒）',
               existing_nullable=True)
    op.alter_column('interview_question', 'ai_score',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='AI评分 1-5',
               existing_nullable=True)
    op.alter_column('interview_question', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('interview_question', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'interview_question',
        existing_comment='面试题目表',
        schema=None
    )
    op.alter_column('interview_report', 'interview_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联面试ID',
               existing_nullable=False)
    op.alter_column('interview_report', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('interview_report', 'follow_up_count',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='追问次数（冗余）',
               existing_comment='追问次数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview_report', 'total_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='面试总时长(秒)',
               existing_comment='面试总时长（秒）',
               existing_nullable=True)
    op.alter_column('interview_report', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'interview_report',
        existing_comment='面试报告表',
        schema=None
    )
    op.alter_column('message', 'type',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='1-系统 2-评论 3-点赞 4-关注 5-面试 6-私信',
               existing_comment='1-系统 2-评论 3-点赞 4-关注 5-私信',
               existing_nullable=False)
    op.alter_column('message', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='消息标题',
               existing_nullable=False)
    op.alter_column('message', 'content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('message', 'related_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联实体ID',
               existing_comment='关联实体 ID',
               existing_nullable=True)
    op.alter_column('message', 'related_type',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='1-帖子 2-报告 3-用户',
               existing_nullable=True)
    op.alter_column('message', 'is_read',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='0-未读 1-已读',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('message', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_type'), table_name='message')
    op.drop_index(op.f('idx_user_unread'), table_name='message')
    op.drop_table_comment(
        'message',
        existing_comment='消息通知表',
        schema=None
    )
    op.alter_column('outbox_event', 'status',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='0-待发布 1-已发布 2-死信(重试超限)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('outbox_event', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_published'), table_name='outbox_event')
    op.drop_index(op.f('idx_status_retry'), table_name='outbox_event')
    op.drop_table_comment(
        'outbox_event',
        existing_comment='事务性Outbox事件表（业务变更与事件同事务落库，异步投递MQ）',
        schema=None
    )
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='帖子标题',
               existing_nullable=False)
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='帖子正文',
               existing_nullable=False)
    op.alter_column('post', 'tags',
               existing_type=mysql.JSON(),
               comment='标签列表（展示用冗余缓存）',
               existing_comment='标签列表（展示用冗余缓存，避免列表查询 JOIN；以 post_tag 表为筛选数据源）',
               existing_nullable=True)
    op.alter_column('post', 'is_pinned',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='是否置顶 0-否 1-是',
               existing_comment='是否置顶',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('post', 'is_hot',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='是否热门 0-否 1-是',
               existing_comment='是否热门',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('post', 'status',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='0-删除 1-正常',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('post', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_author_id'), table_name='post')
    op.drop_index(op.f('idx_created_at'), table_name='post')
    op.drop_index(op.f('idx_status_hot'), table_name='post')
    op.drop_index(op.f('idx_status_pinned'), table_name='post')
    op.drop_table_comment(
        'post',
        existing_comment='社区帖子表',
        schema=None
    )
    op.alter_column('post_favorite', 'post_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='帖子ID',
               existing_nullable=False)
    op.alter_column('post_favorite', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='收藏用户ID',
               existing_nullable=False)
    op.alter_column('post_favorite', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='收藏时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_id'), table_name='post_favorite')
    op.drop_index(op.f('uk_post_user'), table_name='post_favorite')
    op.drop_table_comment(
        'post_favorite',
        existing_comment='帖子收藏表',
        schema=None
    )
    op.alter_column('post_like', 'post_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='帖子ID',
               existing_nullable=False)
    op.alter_column('post_like', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='点赞用户ID',
               existing_nullable=False)
    op.alter_column('post_like', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='点赞时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_id'), table_name='post_like')
    op.drop_index(op.f('uk_post_user'), table_name='post_like')
    op.drop_table_comment(
        'post_like',
        existing_comment='帖子点赞表',
        schema=None
    )
    op.alter_column('post_tag', 'post_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='帖子ID',
               existing_nullable=False)
    op.alter_column('post_tag', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_tag'), table_name='post_tag')
    op.drop_index(op.f('uk_post_tag'), table_name='post_tag')
    op.drop_table_comment(
        'post_tag',
        existing_comment='帖子标签关联表',
        schema=None
    )
    op.alter_column('resume', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('resume', 'status',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='0-解析中 1-就绪 2-错误',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('resume', 'parsed_education',
               existing_type=mysql.JSON(),
               comment='解析出的教育经历数组',
               existing_comment='解析出的教育经历数组（支持多段，元素含 school/degree/major/year）',
               existing_nullable=True)
    op.alter_column('resume', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resume', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'resume',
        existing_comment='简历表',
        schema=None
    )
    op.alter_column('resume_work_experience', 'resume_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联简历ID',
               existing_nullable=False)
    op.alter_column('resume_work_experience', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'resume_work_experience',
        existing_comment='简历工作经历表',
        schema=None
    )
    op.alter_column('upload_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('upload_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'upload_records',
        existing_comment='文件上传记录表',
        schema=None
    )
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='用户昵称',
               existing_nullable=False)
    op.alter_column('user', 'avatar',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('user', 'gender',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               nullable=False,
               existing_comment='0-未设置 1-男 2-女',
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'birthday',
               existing_type=sa.DATE(),
               comment='生日',
               existing_nullable=True)
    op.alter_column('user', 'bio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=False,
               comment='个人简介',
               existing_server_default=sa.text("''"))
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='所在地',
               existing_nullable=True)
    op.alter_column('user', 'profile_visibility',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='资料可见性 0-公开 1-仅关注者 2-仅自己',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'status',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='0-禁用 1-正常 2-注销',
               existing_comment='0-禁用 1-正常',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'user',
        existing_comment='用户表',
        schema=None
    )
    op.alter_column('user_activity', 'type',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='1-点赞 2-评论 3-关注 4-发帖',
               existing_nullable=False)
    op.alter_column('user_activity', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_created'), table_name='user_activity')
    op.drop_table_comment(
        'user_activity',
        existing_comment='用户动态表',
        schema=None
    )
    op.alter_column('user_auth', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联user表',
               existing_comment='关联 user 表',
               existing_nullable=False)
    op.alter_column('user_auth', 'provider',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='1-邮箱 2-GitHub 3-QQ(预留) 4-微信(预留)',
               existing_nullable=False)
    op.drop_index(op.f('idx_user_id'), table_name='user_auth')
    op.drop_index(op.f('uk_provider_user'), table_name='user_auth')
    op.create_index(op.f('ix_user_auth_user_id'), 'user_auth', ['user_id'], unique=False)
    op.drop_table_comment(
        'user_auth',
        existing_comment='用户认证方式映射表',
        schema=None
    )
    op.alter_column('user_follow', 'follower_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关注者用户ID',
               existing_comment='关注者',
               existing_nullable=False)
    op.alter_column('user_follow', 'following_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='被关注者用户ID',
               existing_comment='被关注者',
               existing_nullable=False)
    op.alter_column('user_follow', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='关注时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_follower_created'), table_name='user_follow')
    op.drop_index(op.f('idx_following_created'), table_name='user_follow')
    op.drop_index(op.f('uk_follower_following'), table_name='user_follow')
    op.drop_table_comment(
        'user_follow',
        existing_comment='用户关注关系表',
        schema=None
    )
    op.alter_column('user_settings', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_settings', 'email_notify',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='邮件通知 0-关 1-开',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'push_notify',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='推送通知',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'sound_enabled',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='声音提示',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'public_profile',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='公开个人主页',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_settings', 'visibility_gender',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='性别可见 0-不可见 1-可见',
               existing_comment='性别可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'visibility_birthday',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='生日可见 0-不可见 1-可见',
               existing_comment='生日可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'visibility_bio',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='简介可见 0-不可见 1-可见',
               existing_comment='简介可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'visibility_location',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='所在地可见 0-不可见 1-可见',
               existing_comment='所在地可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'visibility_phone',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               comment='手机号可见 0-不可见 1-可见',
               existing_comment='手机号可见（默认不可见）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'user_settings',
        existing_comment='用户设置表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_settings',
        '用户设置表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_settings', 'visibility_phone',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='手机号可见（默认不可见）',
               existing_comment='手机号可见 0-不可见 1-可见',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_settings', 'visibility_location',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='所在地可见',
               existing_comment='所在地可见 0-不可见 1-可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'visibility_bio',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='简介可见',
               existing_comment='简介可见 0-不可见 1-可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'visibility_birthday',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='生日可见',
               existing_comment='生日可见 0-不可见 1-可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'visibility_gender',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='性别可见',
               existing_comment='性别可见 0-不可见 1-可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'public_profile',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='公开个人主页',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_settings', 'sound_enabled',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='声音提示',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'push_notify',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='推送通知',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'email_notify',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='邮件通知 0-关 1-开',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.create_table_comment(
        'user_follow',
        '用户关注关系表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_follower_following'), 'user_follow', ['follower_id', 'following_id'], unique=True)
    op.create_index(op.f('idx_following_created'), 'user_follow', ['following_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_follower_created'), 'user_follow', ['follower_id', 'created_at'], unique=False)
    op.alter_column('user_follow', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='关注时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_follow', 'following_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='被关注者',
               existing_comment='被关注者用户ID',
               existing_nullable=False)
    op.alter_column('user_follow', 'follower_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关注者',
               existing_comment='关注者用户ID',
               existing_nullable=False)
    op.create_table_comment(
        'user_auth',
        '用户认证方式映射表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_auth_user_id'), table_name='user_auth')
    op.create_index(op.f('uk_provider_user'), 'user_auth', ['provider', 'provider_user_id'], unique=True)
    op.create_index(op.f('idx_user_id'), 'user_auth', ['user_id'], unique=False)
    op.alter_column('user_auth', 'provider',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='1-邮箱 2-GitHub 3-QQ(预留) 4-微信(预留)',
               existing_nullable=False)
    op.alter_column('user_auth', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联 user 表',
               existing_comment='关联user表',
               existing_nullable=False)
    op.create_table_comment(
        'user_activity',
        '用户动态表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_created'), 'user_activity', ['user_id', 'created_at'], unique=False)
    op.alter_column('user_activity', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_activity', 'type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='1-点赞 2-评论 3-关注 4-发帖',
               existing_nullable=False)
    op.create_table_comment(
        'user',
        '用户表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='0-禁用 1-正常',
               existing_comment='0-禁用 1-正常 2-注销',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'profile_visibility',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='资料可见性 0-公开 1-仅关注者 2-仅自己',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment=None,
               existing_comment='所在地',
               existing_nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'bio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=True,
               comment=None,
               existing_comment='个人简介',
               existing_server_default=sa.text("''"))
    op.alter_column('user', 'birthday',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生日',
               existing_nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               nullable=True,
               existing_comment='0-未设置 1-男 2-女',
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'avatar',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='用户昵称',
               existing_nullable=False)
    op.create_table_comment(
        'upload_records',
        '文件上传记录表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('upload_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('upload_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'resume_work_experience',
        '简历工作经历表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('resume_work_experience', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resume_work_experience', 'resume_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='关联简历ID',
               existing_nullable=False)
    op.create_table_comment(
        'resume',
        '简历表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('resume', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('resume', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resume', 'parsed_education',
               existing_type=mysql.JSON(),
               comment='解析出的教育经历数组（支持多段，元素含 school/degree/major/year）',
               existing_comment='解析出的教育经历数组',
               existing_nullable=True)
    op.alter_column('resume', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='0-解析中 1-就绪 2-错误',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('resume', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.create_table_comment(
        'post_tag',
        '帖子标签关联表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_post_tag'), 'post_tag', ['post_id', 'tag'], unique=True)
    op.create_index(op.f('idx_tag'), 'post_tag', ['tag', 'created_at'], unique=False)
    op.alter_column('post_tag', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post_tag', 'post_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='帖子ID',
               existing_nullable=False)
    op.create_table_comment(
        'post_like',
        '帖子点赞表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_post_user'), 'post_like', ['post_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_user_id'), 'post_like', ['user_id'], unique=False)
    op.alter_column('post_like', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='点赞时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post_like', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='点赞用户ID',
               existing_nullable=False)
    op.alter_column('post_like', 'post_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='帖子ID',
               existing_nullable=False)
    op.create_table_comment(
        'post_favorite',
        '帖子收藏表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_post_user'), 'post_favorite', ['post_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_user_id'), 'post_favorite', ['user_id', 'created_at'], unique=False)
    op.alter_column('post_favorite', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='收藏时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post_favorite', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='收藏用户ID',
               existing_nullable=False)
    op.alter_column('post_favorite', 'post_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='帖子ID',
               existing_nullable=False)
    op.create_table_comment(
        'post',
        '社区帖子表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_status_pinned'), 'post', ['status', 'is_pinned', 'created_at'], unique=False)
    op.create_index(op.f('idx_status_hot'), 'post', ['status', 'is_hot', 'likes_count'], unique=False)
    op.create_index(op.f('idx_created_at'), 'post', ['status', 'created_at'], unique=False)
    op.create_index(op.f('idx_author_id'), 'post', ['author_id'], unique=False)
    op.alter_column('post', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('post', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='0-删除 1-正常',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('post', 'is_hot',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='是否热门',
               existing_comment='是否热门 0-否 1-是',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('post', 'is_pinned',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='是否置顶',
               existing_comment='是否置顶 0-否 1-是',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('post', 'tags',
               existing_type=mysql.JSON(),
               comment='标签列表（展示用冗余缓存，避免列表查询 JOIN；以 post_tag 表为筛选数据源）',
               existing_comment='标签列表（展示用冗余缓存）',
               existing_nullable=True)
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='帖子正文',
               existing_nullable=False)
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='帖子标题',
               existing_nullable=False)
    op.create_table_comment(
        'outbox_event',
        '事务性Outbox事件表（业务变更与事件同事务落库，异步投递MQ）',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_status_retry'), 'outbox_event', ['status', 'next_retry_at', 'id'], unique=False)
    op.create_index(op.f('idx_published'), 'outbox_event', ['status', 'published_at'], unique=False)
    op.alter_column('outbox_event', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('outbox_event', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='0-待发布 1-已发布 2-死信(重试超限)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_table_comment(
        'message',
        '消息通知表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_unread'), 'message', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('idx_user_type'), 'message', ['user_id', 'type', 'created_at'], unique=False)
    op.alter_column('message', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('message', 'is_read',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='0-未读 1-已读',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('message', 'related_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='1-帖子 2-报告 3-用户',
               existing_nullable=True)
    op.alter_column('message', 'related_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='关联实体 ID',
               existing_comment='关联实体ID',
               existing_nullable=True)
    op.alter_column('message', 'content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('message', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='消息标题',
               existing_nullable=False)
    op.alter_column('message', 'type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='1-系统 2-评论 3-点赞 4-关注 5-私信',
               existing_comment='1-系统 2-评论 3-点赞 4-关注 5-面试 6-私信',
               existing_nullable=False)
    op.create_table_comment(
        'interview_report',
        '面试报告表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('interview_report', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('interview_report', 'total_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='面试总时长（秒）',
               existing_comment='面试总时长(秒)',
               existing_nullable=True)
    op.alter_column('interview_report', 'follow_up_count',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='追问次数',
               existing_comment='追问次数（冗余）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview_report', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('interview_report', 'interview_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='关联面试ID',
               existing_nullable=False)
    op.create_table_comment(
        'interview_question',
        '面试题目表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('interview_question', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('interview_question', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('interview_question', 'ai_score',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='AI评分 1-5',
               existing_nullable=True)
    op.alter_column('interview_question', 'thinking_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='思考时长（秒）',
               existing_comment='思考时长(秒)',
               existing_nullable=True)
    op.alter_column('interview_question', 'answer_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='回答时长（秒）',
               existing_comment='回答时长(秒)',
               existing_nullable=True)
    op.alter_column('interview_question', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='用户回答',
               existing_comment='用户回答文本',
               existing_nullable=True)
    op.alter_column('interview_question', 'question_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='题目内容',
               existing_nullable=False)
    op.alter_column('interview_question', 'parent_question_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='父题目ID（追问关联，指向 interview_question.id）',
               existing_comment='父题目ID（追问关联）',
               existing_nullable=True)
    op.alter_column('interview_question', 'is_follow_up',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='是否追问题 0-否 1-是',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview_question', 'category',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='题目维度 1-技术基础 2-项目经验 3-综合素质 4-架构设计',
               existing_nullable=True)
    op.alter_column('interview_question', 'question_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='1-技术题 2-项目题 3-行为题',
               existing_nullable=False)
    op.alter_column('interview_question', 'interview_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='关联面试ID',
               existing_nullable=False)
    op.create_table_comment(
        'interview',
        '面试会话表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('interview', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('interview', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('interview', 'device_check_passed',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               comment='设备检测是否通过 0-未通过 1-已通过',
               existing_comment='设备检测是否通过',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview', 'follow_up_count',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='追问次数',
               existing_comment='追问次数（冗余计数）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview', 'total_duration',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='面试总时长（秒）',
               existing_comment='面试总时长(秒)',
               existing_nullable=True)
    op.alter_column('interview', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='0-进行中 1-已完成 2-已中断',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('interview', 'type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='1-完整面试 2-快速面试',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('interview', 'resume_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='使用的简历 ID',
               existing_comment='使用的简历ID',
               existing_nullable=False)
    op.alter_column('interview', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.create_table_comment(
        'dm_message',
        '私信消息表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('dm_message', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='发送时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('dm_message', 'is_read',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='0-未读 1-已读',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('dm_message', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('dm_message', 'from_user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='发送者',
               existing_comment='发送者用户ID',
               existing_nullable=False)
    op.alter_column('dm_message', 'conversation_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='关联会话ID',
               existing_nullable=False)
    op.create_table_comment(
        'dm_conversation',
        '私信会话表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('dm_conversation', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('dm_conversation', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('dm_conversation', 'user2_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='另一用户ID',
               existing_nullable=False)
    op.alter_column('dm_conversation', 'user1_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='较小用户 ID（约定 user1_id < user2_id）',
               existing_comment='较小用户ID',
               existing_nullable=False)
    op.create_table('post_comment',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=False),
    sa.Column('likes_count', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='点赞数'),
    sa.Column('status', mysql.TINYINT(unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='0-删除 1-正常'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间（用于评论编辑审计）'),
    sa.PrimaryKeyConstraint('id'),
    comment='帖子评论表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='帖子评论表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_post_id'), 'post_comment', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_author_id'), 'post_comment', ['author_id'], unique=False)
    op.drop_table('comment')
    # ### end Alembic commands ###
