"""提示词包，统一导出各业务提示词。"""

from app.llm.prompt.index import (
    COMPLETENESS_LOGIC_PROMPT,
    CONTENT_ANALYSIS_PROMPT,
    FAST_DECISION_PROMPT,
    FOLLOW_UP_STREAM_PROMPT,
    QUESTION_GENERATION_PROMPT,
    REPORT_SUMMARY_PROMPT,
    RESUME_PARSE_PROMPT,
    SCORING_PROMPT,
    SPEECH_CORRECTION_PROMPT,
    TECHNICAL_DEPTH_PROMPT,
)

__all__ = [
    "COMPLETENESS_LOGIC_PROMPT",
    "CONTENT_ANALYSIS_PROMPT",
    "FAST_DECISION_PROMPT",
    "FOLLOW_UP_STREAM_PROMPT",
    "QUESTION_GENERATION_PROMPT",
    "REPORT_SUMMARY_PROMPT",
    "RESUME_PARSE_PROMPT",
    "SCORING_PROMPT",
    "SPEECH_CORRECTION_PROMPT",
    "TECHNICAL_DEPTH_PROMPT",
]
