"""提示词包，统一导出各业务提示词。"""

from app.llm.prompt.index import (
    ANSWER_ANALYSIS_PROMPT,
    FAST_DECISION_PROMPT,
    QUESTION_GENERATION_PROMPT,
    REPORT_SUMMARY_PROMPT,
    RESUME_PARSE_PROMPT,
    SPEECH_CORRECTION_PROMPT,
)

__all__ = [
    "ANSWER_ANALYSIS_PROMPT",
    "FAST_DECISION_PROMPT",
    "QUESTION_GENERATION_PROMPT",
    "REPORT_SUMMARY_PROMPT",
    "RESUME_PARSE_PROMPT",
    "SPEECH_CORRECTION_PROMPT",
]
